[package]
description = "Universal Web Game native runtime host"
edition = "2021"
license = "MIT"
name = "ugr-cli"
version = "0.1.0"

[dependencies]
serde_json = "=1.0.151"
tokio = { version = "=1.53.1", features = ["rt", "time", "net"] }
ugr-compositor = { path = "../ugr-compositor" }
ugr-runtime = {path = "../ugr-runtime"}
ugr-html = {path = "../ugr-html"}
ugr-ui = {path = "../ugr-ui"}
ugr-webgl = {path = "../ugr-webgl"}
ugr-wgpu = {path = "../ugr-wgpu"}
winit = "=0.30.13"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
