
(() => {
  const id = () => Deno.core.ops.op_alloc_resource();
  globalThis.__ugr_webgl_commands = [];
  globalThis.__ugr_webgpu_commands = [];
  globalThis.__ugr_canvas_commands = [];
  const record = (op, args = []) => __ugr_webgl_commands.push({ op, args });
  const resource = (kind) => ({ id: Deno.core.ops.op_alloc_resource(), kind });
  const extensions = ["OES_element_index_uint", "OES_vertex_array_object", "WEBGL_depth_texture", "EXT_texture_filter_anisotropic", "EXT_color_buffer_float"];
  const createCanvas2DContext = () => {
    const state = { fillStyle: "#000000", strokeStyle: "#000000", lineWidth: 1, globalAlpha: 1, stack: [] };
    const record2d = (op, args = []) => __ugr_canvas_commands.push({ op, args });
    const color = (value) => { const m = String(value).match(/^#([0-9a-f]{6})$/i); return m ? [parseInt(m[1].slice(0, 2), 16) / 255, parseInt(m[1].slice(2, 4), 16) / 255, parseInt(m[1].slice(4, 6), 16) / 255, state.globalAlpha] : [0, 0, 0, state.globalAlpha]; };
    return { get fillStyle() { return state.fillStyle; }, set fillStyle(v) { state.fillStyle = String(v); }, get strokeStyle() { return state.strokeStyle; }, set strokeStyle(v) { state.strokeStyle = String(v); }, get lineWidth() { return state.lineWidth; }, set lineWidth(v) { state.lineWidth = Number(v) || 1; }, get globalAlpha() { return state.globalAlpha; }, set globalAlpha(v) { state.globalAlpha = Math.max(0, Math.min(1, Number(v))); }, fillRect(x, y, w, h) { record2d("fillRect", [x, y, w, h, color(state.fillStyle)]); }, clearRect(x, y, w, h) { record2d("clearRect", [x, y, w, h]); }, beginPath() { record2d("beginPath"); }, moveTo(x, y) { record2d("moveTo", [x, y]); }, lineTo(x, y) { record2d("lineTo", [x, y]); }, stroke() { record2d("stroke", [color(state.strokeStyle), state.lineWidth]); }, fill() { record2d("fill", [color(state.fillStyle)]); }, save() { state.stack.push([state.fillStyle, state.strokeStyle, state.lineWidth, state.globalAlpha]); record2d("save"); }, restore() { const v = state.stack.pop(); if (v) [state.fillStyle, state.strokeStyle, state.lineWidth, state.globalAlpha] = v; record2d("restore"); }, setTransform(a, b, c, d, e, f) { record2d("setTransform", [a, b, c, d, e, f]); }, resetTransform() { record2d("setTransform", [1, 0, 0, 1, 0, 0]); } };
  };

  const createWebGlContext = (version, attributes = {}) => {
    const is2 = version === "webgl2";
    const state = { buffers: {}, textures: {}, vao: null, framebuffer: null, program: null, arrayBuffer: null, elementBuffer: null };
    const gl = {
      version, drawingBufferWidth: 1, drawingBufferHeight: 1,
      getContextAttributes() { return { alpha: attributes.alpha !== false, antialias: attributes.antialias !== false, depth: attributes.depth !== false, stencil: !!attributes.stencil, preserveDrawingBuffer: !!attributes.preserveDrawingBuffer }; },
      getSupportedExtensions() { return extensions.slice(); }, getExtension(name) { return extensions.includes(name) ? { name } : null; },
      getError() { return 0; }, isContextLost() { return false; },
      createBuffer() { const v = resource("buffer"); state.buffers[v.id] = { data: [] }; return v; },
    deleteBuffer(v) { if (v) { delete state.buffers[v.id]; Deno.core.ops.op_release_buffer(v.id); } record("deleteBuffer", [v?.id || 0]); },
      bindBuffer(target, v) { if (target === 0x8892) state.arrayBuffer = v; if (target === 0x8893) state.elementBuffer = v; record("bindBuffer", [target, v?.id || 0]); },
    bufferData(target, data, usage) { const v = target === 0x8893 ? state.elementBuffer : state.arrayBuffer; if (v && ArrayBuffer.isView(data)) { state.buffers[v.id].byteLength = data.byteLength; const bytes = new Uint8Array(data.buffer, data.byteOffset, data.byteLength); Deno.core.ops.op_upload_buffer(v.id, target, usage || 0, bytes); record("bufferData", [target, data.byteLength, usage || 0]); } else { record("bufferData", [target, Number(data) || 0, usage || 0]); } },
    bufferSubData(target, offset, data) { const v = target === 0x8893 ? state.elementBuffer : state.arrayBuffer; if (v && ArrayBuffer.isView(data)) { const bytes = new Uint8Array(data.buffer, data.byteOffset, data.byteLength); Deno.core.ops.op_upload_buffer(v.id, target, 0, bytes); } record("bufferSubData", [target, offset, data?.byteLength || 0]); },
      createTexture() { return resource("texture"); }, deleteTexture(v) { if (v) Deno.core.ops.op_release_resource(v.id); record("deleteTexture", [v?.id || 0]); }, bindTexture(target, v) { state.texture = v; record("bindTexture", [target, v?.id || 0]); },
      texImage2D(...args) { const data = args[args.length - 1]; if (state.texture && ArrayBuffer.isView(data)) { const bytes = new Uint8Array(data.buffer, data.byteOffset, data.byteLength); Deno.core.ops.op_upload_texture(state.texture.id, bytes); } record("texImage2D", args.slice(0, -1).concat(ArrayBuffer.isView(data) ? data.byteLength : data)); }, texParameteri(target, pname, param) { record("texParameteri", [target, pname, param]); },
      texStorage2D(target, levels, internalFormat, width, height) { if (is2) record("texStorage2D", [target, levels, internalFormat, width, height]); }, generateMipmap(target) { record("generateMipmap", [target]); }, activeTexture(texture) { record("activeTexture", [texture]); }, readPixels(...args) { record("readPixels", args.map((v) => ArrayBuffer.isView(v) ? Array.from(v) : v)); },
      createShader(type) { const v = resource("shader"); v.type = type; v.source = ""; return v; }, shaderSource(v, source) { if (v) { v.source = String(source); Deno.core.ops.op_set_shader_source(v.id, v.source); } record("shaderSource", [v?.id || 0, String(source)]); }, compileShader(v) { if (v) v.compiled = true; record("compileShader", [v?.id || 0]); },
      getShaderParameter(v, p) { return p === 0x8B81 ? !!v?.compiled : true; }, getShaderInfoLog() { return ""; }, deleteShader(v) { record("deleteShader", [v?.id || 0]); },
      createProgram() { return resource("program"); }, attachShader(p, s) { record("attachShader", [p?.id || 0, s?.id || 0]); }, linkProgram(p) { if (p) p.linked = true; record("linkProgram", [p?.id || 0]); }, getProgramParameter(p, q) { return q === 0x8B82 ? !!p?.linked : true; }, getProgramInfoLog() { return ""; }, useProgram(p) { state.program = p; record("useProgram", [p?.id || 0]); }, deleteProgram(p) { record("deleteProgram", [p?.id || 0]); },
      createFramebuffer() { return resource("framebuffer"); }, bindFramebuffer(target, v) { state.framebuffer = v; record("bindFramebuffer", [target, v?.id || 0]); }, deleteFramebuffer(v) { record("deleteFramebuffer", [v?.id || 0]); },
      createRenderbuffer() { return resource("renderbuffer"); }, bindRenderbuffer(target, v) { record("bindRenderbuffer", [target, v?.id || 0]); }, renderbufferStorage(...args) { record("renderbufferStorage", args); },
      createVertexArray() { return is2 ? resource("vertexArray") : null; }, bindVertexArray(v) { state.vao = v; record("bindVertexArray", [v?.id || 0]); }, deleteVertexArray(v) { record("deleteVertexArray", [v?.id || 0]); },
      enableVertexAttribArray(i) { record("enableVertexAttribArray", [i]); }, disableVertexAttribArray(i) { record("disableVertexAttribArray", [i]); }, vertexAttribPointer(...args) { record("vertexAttribPointer", args); }, vertexAttribDivisor(i, d) { if (is2) record("vertexAttribDivisor", [i, d]); },
      getAttribLocation(p, name) { return { id: id(), program: p?.id || 0, name: String(name) }; }, vertexAttrib1f(i, x) { record("vertexAttrib1f", [i?.id || i, x]); }, vertexAttrib2f(i, x, y) { record("vertexAttrib2f", [i?.id || i, x, y]); }, vertexAttrib3f(i, x, y, z) { record("vertexAttrib3f", [i?.id || i, x, y, z]); }, vertexAttrib4f(i, x, y, z, w) { record("vertexAttrib4f", [i?.id || i, x, y, z, w]); },
      viewport(x, y, w, h) { record("viewport", [x, y, w, h]); }, scissor(x, y, w, h) { record("scissor", [x, y, w, h]); }, enable(cap) { record("enable", [cap]); }, disable(cap) { record("disable", [cap]); }, blendFunc(s, d) { record("blendFunc", [s, d]); }, depthFunc(f) { record("depthFunc", [f]); },
      clearColor(r, g, b, a) { record("clearColor", [r, g, b, a]); }, clearDepth(v) { record("clearDepth", [v]); }, clearStencil(v) { record("clearStencil", [v]); }, clear(mask) { record("clear", [mask === undefined ? 0x4000 : mask]); },
      drawArrays(mode, first, count) { record("drawArrays", [mode, first, count]); }, drawElements(mode, count, type, offset) { record("drawElements", [mode, count, type, offset]); }, drawArraysInstanced(mode, first, count, instances) { if (is2) record("drawArraysInstanced", [mode, first, count, instances]); },
      uniform1f(loc, x) { record("uniform1f", [loc?.id || 0, x]); }, uniform4f(loc, a, b, c, d) { record("uniform4f", [loc?.id || 0, a, b, c, d]); }, uniformMatrix4fv(loc, transpose, value) { record("uniformMatrix4fv", [loc?.id || 0, !!transpose, Array.from(value || [])]); }, getUniformLocation(p, name) { return { id: id(), program: p?.id || 0, name: String(name) }; },
      TRIANGLES: 0x0004, ARRAY_BUFFER: 0x8892, ELEMENT_ARRAY_BUFFER: 0x8893, STATIC_DRAW: 0x88E4, FLOAT: 0x1406, UNSIGNED_SHORT: 0x1403, UNSIGNED_INT: 0x1405, COLOR_BUFFER_BIT: 0x4000, DEPTH_BUFFER_BIT: 0x0100, STENCIL_BUFFER_BIT: 0x0400, DEPTH_TEST: 0x0B71, BLEND: 0x0BE2,
    };
    return gl;
  };

  class GPUBuffer { constructor(d = {}) { this.id = id(); this.size = d.size || 0; this.usage = d.usage || 0; this.destroyed = false; } destroy() { this.destroyed = true; __ugr_webgpu_commands.push({ op: "destroyBuffer", id: this.id }); } }
  class GPUTexture { constructor(d = {}) { this.id = id(); this.width = d.size?.width || d.size || 1; this.height = d.size?.height || 1; this.format = d.format || "rgba8unorm"; } createView(d = {}) { return { id: id(), texture: this.id, descriptor: d }; } destroy() { Deno.core.ops.op_release_resource(this.id); __ugr_webgpu_commands.push({ op: "destroyTexture", id: this.id }); } }
  class GPUShaderModule { constructor(d = {}) { this.id = id(); this.code = String(d.code || ""); Deno.core.ops.op_set_shader_source(this.id, this.code); } }
  class GPURenderPipeline { constructor(d = {}) { this.id = id(); this.descriptor = d; Deno.core.ops.op_register_pipeline(this.id, JSON.stringify(d)); __ugr_webgpu_commands.push({ op: "createRenderPipeline", pipeline: this.id, descriptor: d }); } }
  class GPUCommandBuffer { constructor(commands) { this.id = id(); this.commands = commands; } }
  class GPURenderPassEncoder { constructor(commands, descriptor) { this.commands = commands; this.descriptor = descriptor; } setPipeline(p) { this.commands.push({ op: "setPipeline", pipeline: p?.id || 0 }); } setVertexBuffer(slot, b, offset = 0, size) { this.commands.push({ op: "setVertexBuffer", slot, buffer: b?.id || 0, offset, size }); } draw(vertexCount, instanceCount = 1, firstVertex = 0, firstInstance = 0) { this.commands.push({ op: "draw", vertexCount, instanceCount, firstVertex, firstInstance }); } drawIndexed(indexCount, instanceCount = 1, firstIndex = 0, baseVertex = 0, firstInstance = 0) { this.commands.push({ op: "drawIndexed", indexCount, instanceCount, firstIndex, baseVertex, firstInstance }); } end() { this.commands.push({ op: "endRenderPass" }); } }
  class GPUCommandEncoder { constructor() { this.commands = []; } beginRenderPass(d = {}) { this.commands.push({ op: "beginRenderPass", descriptor: d }); return new GPURenderPassEncoder(this.commands, d); } beginComputePass(d = {}) { this.commands.push({ op: "beginComputePass", descriptor: d }); return { setPipeline: (p) => this.commands.push({ op: "setComputePipeline", pipeline: p?.id || 0 }), dispatchWorkgroups: (x, y = 1, z = 1) => this.commands.push({ op: "dispatchWorkgroups", x, y, z }), end: () => this.commands.push({ op: "endComputePass" }) }; } copyBufferToBuffer(src, so, dst, doff, size) { this.commands.push({ op: "copyBufferToBuffer", src: src?.id || 0, so, dst: dst?.id || 0, doff, size }); } finish() { return new GPUCommandBuffer(this.commands.slice()); } }
  class GPUCanvasContext { constructor(canvas) { this.canvas = canvas; this.configuration = null; } configure(d) { this.configuration = d; } unconfigure() { this.configuration = null; } getCurrentTexture() { return new GPUTexture({ size: { width: this.canvas.width || 1, height: this.canvas.height || 1 }, format: this.configuration?.format || "bgra8unorm-srgb" }); } }
  const queue = { writeBuffer(buffer, offset, data) { const bytes = ArrayBuffer.isView(data) ? new Uint8Array(data.buffer, data.byteOffset, data.byteLength) : data; if (buffer && ArrayBuffer.isView(bytes)) Deno.core.ops.op_upload_buffer(buffer.id, 0, buffer.usage || 0, bytes); __ugr_webgpu_commands.push({ op: "writeBuffer", buffer: buffer?.id || 0, offset, byteLength: bytes?.byteLength || 0 }); }, writeTexture(destination, data, layout, size) { const bytes = ArrayBuffer.isView(data) ? new Uint8Array(data.buffer, data.byteOffset, data.byteLength) : data; __ugr_webgpu_commands.push({ op: "writeTexture", destination, byteLength: bytes?.byteLength || 0, layout, size }); }, submit(buffers) { for (const b of buffers || []) __ugr_webgpu_commands.push(...(b?.commands || [])); }, onSubmittedWorkDone() { return Promise.resolve(); } };
  const device = { queue, lost: Promise.resolve({ reason: "destroyed", message: "" }), createBuffer(d) { return new GPUBuffer(d); }, createTexture(d) { return new GPUTexture(d); }, createSampler(d) { return { id: id(), descriptor: d }; }, createShaderModule(d) { return new GPUShaderModule(d); }, createRenderPipeline(d) { if (!d?.vertex) throw new TypeError("render pipeline requires a vertex stage"); return new GPURenderPipeline(d); }, createComputePipeline(d) { if (!d?.compute) throw new TypeError("compute pipeline requires a compute stage"); const p = { id: id(), descriptor: d }; Deno.core.ops.op_register_pipeline(p.id, JSON.stringify(d)); return p; }, createCommandEncoder() { return new GPUCommandEncoder(); }, createBindGroupLayout(d) { return { id: id(), descriptor: d }; }, createBindGroup(d) { return { id: id(), descriptor: d }; }, createPipelineLayout(d) { return { id: id(), descriptor: d }; } };
  const adapter = { name: "UGR D3D12 Adapter", features: new Set(), limits: { maxTextureDimension2D: 16384 }, isFallbackAdapter: false, requestDevice() { return device; } };
  const gpu = { requestAdapter() { return adapter; }, getPreferredCanvasFormat() { return "bgra8unorm-srgb"; } };
  globalThis.document = { createElement(tag) { return tag === "canvas" ? (() => { const canvas = { width: 1, height: 1, getContext(kind, attrs) { if (kind === "webgl" || kind === "experimental-webgl") return createWebGlContext("webgl", attrs); if (kind === "webgl2") return createWebGlContext("webgl2", attrs); if (kind === "webgpu") return new GPUCanvasContext(canvas); if (kind === "2d") return createCanvas2DContext(); return null; } }; return canvas; })() : {}; } };
  globalThis.navigator = { gpu };
})();
    
